<?php
/**
 * Created by PhpStorm.
 * User: spbaniya
 * Date: 11/13/17
 * Time: 2:12 PM
 */

namespace App\Requests;


class Request extends \Slim\Http\Request
{

    public function getParams(array $only = null)
    {
        print_r($this->getAttribute('route'));//return parent::getParams($only); // TODO: Change the autogenerated stub
    }
}